### ISSUE TITLE
`Date` property discards nanoseconds

### ISSUE THREAD

**Issue by stephencelis** [juri/Parse3339#8]
When incorporating some of your fun improvements in our parser combinator demo [here](https://github.com/pointfreeco/swift-parsing/pull/305) I noticed that the `Date` constructor doesn't currently make use of the nanoseconds.

(I think your parser will probably still win out over our combinators even with that fixed, though it may close the gap a little :wink:)

**Comment by juri** [comment]
Fixed in #6 and #9 .

**Comment by stephencelis** [comment]
@juri I think the `.date` helper still does not utilize `.nanoseconds` (date components does just fine, though).

**Comment by juri** [comment]
Oh, heck. Thanks for pointing that out. Will fix.

**Comment by juri** [comment]
Now it should really be fixed.
